kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: nWP7cQFqo+Bk3v9TxBhpSYOUtLluIDtcV7Pz5X1SVas=
      - identity: {}
